#!/usr/bin/env bash
set -euo pipefail

samples_dir="docs/COMPLIANCE_SAMPLES"
test -d "$samples_dir" || { echo "FAIL: missing $samples_dir"; exit 1; }

latest="$(ls -1 "$samples_dir" | sort -r | head -n 1 || true)"
test -n "${latest:-}" || { echo "FAIL: no samples in $samples_dir"; exit 1; }

sample_path="$samples_dir/$latest"
test -f "$sample_path/SUMMARY.md" || { echo "FAIL: missing $sample_path/SUMMARY.md"; exit 1; }
test -f "$sample_path/probe_index.json" || { echo "FAIL: missing $sample_path/probe_index.json"; exit 1; }

if test "${NO_COMMIT:-0}" = "1"; then
  test -f docs/AUTOSCAN.md || { echo "FAIL: missing docs/AUTOSCAN.md"; exit 1; }
  grep -q "$sample_path/SUMMARY.md" docs/AUTOSCAN.md || { echo "FAIL: docs/AUTOSCAN.md not pointing to latest SUMMARY.md ($sample_path)"; exit 1; }
  grep -q "$sample_path/probe_index.json" docs/AUTOSCAN.md || { echo "FAIL: docs/AUTOSCAN.md not pointing to latest probe_index.json ($sample_path)"; exit 1; }
  echo "OK: docs/AUTOSCAN.md already points to latest autoscan."
  exit 0
fi

mkdir -p docs
cat > docs/AUTOSCAN.md <<DOC
# Contract autoscan

Latest saved autoscan:
- Summary: \`$sample_path/SUMMARY.md\`
- Probe index: \`$sample_path/probe_index.json\`

This folder is generated by the autoscan runner and is intended to be referenced from PRs/issues.
DOC

if test -f docs/README.md; then
  grep -q "docs/AUTOSCAN.md" docs/README.md 2>/dev/null || printf "\n- Autoscan: docs/AUTOSCAN.md\n" >> docs/README.md
fi

if test -f README.md; then
  grep -q "docs/AUTOSCAN.md" README.md 2>/dev/null || printf "\n## Docs\n- Autoscan: docs/AUTOSCAN.md\n" >> README.md
fi

log_ts="$(date +%Y-%m-%d\ %H:%M)"
test -f PROJECT_LOG.md || : > PROJECT_LOG.md
printf "\n## %s\n- Pinned latest autoscan in docs/AUTOSCAN.md -> %s (SUMMARY.md + probe_index.json)\n" "$log_ts" "$sample_path" >> PROJECT_LOG.md

git add docs/AUTOSCAN.md PROJECT_LOG.md || true
test -f docs/README.md && git add docs/README.md || true
test -f README.md && git add README.md || true

if git diff --cached --quiet; then
  :
else
  git commit -m "docs: pin latest autoscan link" || true
fi
